runtime: python311
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  ENVIRONMENT: "production"
  PORT: "8080"
  WEB_CONCURRENCY: "1"

entrypoint: gunicorn --chdir . playground:app --bind 0.0.0.0:$PORT

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
