runtime: python311

env_variables:
  PORT: "8080"

entrypoint: gunicorn --chdir . playground:app --bind 0.0.0.0:$PORT

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
