steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/playground', '.']

images:
- 'gcr.io/$PROJECT_ID/playground'

env:
- 'PORT=8080'

runtime: python311
resources:
  memory: 2Gi
  cpu: 1
  diskSizeGb: 10
