steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/playground', '.']
  id: 'build'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/playground']
  id: 'push'

images:
- 'gcr.io/$PROJECT_ID/playground'

env:
- 'PORT=8080'
- 'ENVIRONMENT=production'

runtime: python311

resources:
  memory: 2Gi
  cpu: 1
  diskSizeGb: 10

available_secrets:
  secret_manager:
  - version_name: projects/$PROJECT_ID/secrets/GOOGLE_APPLICATION_CREDENTIALS/latest
    env: GOOGLE_APPLICATION_CREDENTIALS
